apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: hellonode-replicaset
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hellonode
  template:
    metadata:
      labels:
        app: hellonode
        version: v0.1
    spec:
      containers:
      - name: hellonode
        image: hellonode:0.1
        ports:
        - containerPort: 3000
        readinessProbe:
          tcpSocket:
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          tcpSocket:
            port: 3000
          initialDelaySeconds: 15
          periodSeconds: 20
